version: '3.8'  # Remove or update this line if it causes warnings

services:
  app:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 user_auth_project.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/user_auth_db
      - SECRET_KEY=${SECRET_KEY}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=user_auth_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d user_auth_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7

  rabbitmq:
    image: rabbitmq:3.13.7-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: